import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { auth } from '@/lib/auth';
import { SessionProvider, signIn, signOut } from 'next-auth/react';
import { SignInButton } from '@/components/signin-button';
import { SignOutButton } from '@/components/signout-button';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const session = await auth();

	const user = session?.user;
	return (
		<html lang="en">
			<body className={inter.className}>
				<div>
					<div>
						<SignOutButton /> <SignInButton />
					</div>
					<div>
						<>
							<div>Session: </div>
							{children}
						</>
					</div>
				</div>
			</body>
		</html>
	);
}
